openapi: 3.0.1
info:
  title: Coinbase Spot Price API
  version: "1.0.0"
  description: OpenAPI specification for retrieving spot prices via the Coinbase REST API.
servers:
  - url: https://api.coinbase.com
paths:
  /v2/prices/BTC-USD/spot:
    get:
      summary: Retrieve the current spot price for a trading pair
      description: Returns the latest spot price for the BTC-USD trading pair on Coinbase.
      operationId: getSpotPrice
      responses:
        '200':
          description: Successful response containing the current spot price for the requested trading pair.
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    type: string
                  currency:
                    type: string
                  amount:
                    type: string
                required:
                  - base
                  - currency
                  - amount
