name: Sync Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List available action specs
        run: python scripts/update_actions.py
